### ISSUE TITLE
禁用点击广告无效

### ISSUE THREAD

**Issue by jincheng555** [AllLuckly/LBLaunchImageAd#10]
//是否能点击
imgAdView.isClickAdView = NO;
请问为什么禁用点击无效呢？

**Comment by AllLuckly** [comment]
紧急解决方案：可以根据这个在点击事件里面return就可以了



            
            
                
                    
                            
                                
                            
                            
                                435844159
                            
                    
                        
                            
                                    邮箱：435844159@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            在2019年10月16日 16:31，Jason 写道： //是否能点击

imgAdView.isClickAdView = NO;

请问为什么禁用点击无效呢？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/AllLuckly/LBLaunchImageAd/issues/10?email_source=notifications\u0026email_token=ACPH6X5PB7EFJR4VNHF7H33QO3GNHA5CNFSM4JBIBQEKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HSC3ETA",

"url": "https://github.com/AllLuckly/LBLaunchImageAd/issues/10?email_source=notifications\u0026email_token=ACPH6X5PB7EFJR4VNHF7H33QO3GNHA5CNFSM4JBIBQEKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HSC3ETA",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jincheng555** [comment]
并不管用。我直接imgAdView.userInteractionEnabled = NO;了

**Comment by AllLuckly** [comment]
```
case clickAdType:{
    if(不能点击条件){
        return;
    }
    NSLog(@"这里写点击广告逻辑");
}
```

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
